apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${spacename}-wildcard-tls
  namespace: ${namespace}
  labels:
    spacename: ${spacename}
spec:
  secretName: ${spacename}-wildcard-tls
  dnsNames:
    - "${spacename}.${username}.${coder_domain}"
    - "*.${spacename}.${username}.${coder_domain}"
  issuerRef:
    name: letsencrypt-rfc2136
    kind: ClusterIssuer
    group: cert-manager.io
